Adding sdl-tsa-vars.config for adding iot to arcade validation pipeline for running policheck
dotnet/iot pull request #1214
Opened 2020-10-16 22:25 UTC by Anipik

Fixes https://github.com/dotnet/iot/issues/1146
Copied the file from the runtime repo with repo name change and notification email change.
Bug Area path remains same bcoz i don't have appropriate rights to create a new one.

runtime copy https://github.com/dotnet/runtime/blob/master/eng/sdl-tsa-vars.config

2020-10-16 22:59 UTC, adiaaida commented
File looks fine to me, but I'd probably reach out to folks who know how to to see if you want/need a different area path (I'd imagine yes, but I don't actually know).

2020-10-17 08:04 UTC, pgrawehr commented
Just curious: What is policheck? Do you have an example of what messages this generates?

2020-10-17 22:10 UTC, Anipik commented
> Just curious: What is policheck? Do you have an example of what messages this generates?

It scans over the code and flags bad words.

2020-10-18 08:59 UTC, Ellerbach requested changes
I'm all find with policheck all up but you have to add as well a specific readme.MD with information on what is policheck, what it does, an example of the output and also where to find the list of "bad" words.
The added file is very "misterious" from an open source point of view as what it is pointing can't be accessed by anyone to check what it is. So minimum is to add documentation to explain all and a way to report any issue as well.

2020-10-18 08:59 UTC, Ellerbach commented on eng/sdl-tsa-vars.config
> +-TsaPublish $True
you're most likely missing a CR at the end of the line

2020-10-19 19:31 UTC, joperezr reviewed
Thanks for adding this @Anipik. File looks good to me but I do agree with @Ellerbach that if we could add some sort of documentation of what is being added it would be ideal, specifically since it is a check that might potentially break the build, so any docs around policheck and/or how to fix issues would be great 👍

2020-10-19 20:11 UTC, adiaaida commented
I don't know if this file would break the build. While this is not intuitive, this file enables us to run policheck/credscan as part of our external nightly validation pipeline (https://dev.azure.com/dnceng/internal/_build?definitionId=827), which is external to your builds. Credscan/policheck also do not fail the build when they are run if you pass -TsaPublish $True. They will open SDL issues that the team will need to investigate/fix, but it won't fail the build.

2020-10-19 22:36 UTC, joperezr commented
Got it! Thanks for the explanation

2020-10-28 19:06 UTC, Anipik commented
The policheck & credscan tools are internal and are part of a wide global readiness effort. I have reached out to the teams who are responsible for making the documentation public for these tools.

2020-10-28 19:08 UTC, joperezr approved these changes

2020-10-28 19:08 UTC, merged