packages required by .NET Standard only
dotnet/iot pull request #1786
Opened 2022-01-30 13:49 UTC by tibel

Those package references are needed by .NET Standard 2.0 only.
.NET 6.0 includes the needed types already.

2022-01-30 20:03 UTC, pgrawehr approved these changes
I guess CI wouldn't run if the observation wasn't correct. Thanks!

2022-01-31 18:05 UTC, joperezr requested changes
Even though the changes are correct, technically speaking removing a dependency from a framework is considered a breaking change, and given this is in System.Device.Gpio package, I think we should be more hesitant to take these kinds of breaks. For example, I would suggest delaying this for our next major bump release, as doing it now would be a breaking change and violate SemVer

2022-01-31 18:06 UTC, joperezr commented
I really appreciate the contribution @tibel, and again, the changes you are making here are the correct ones, I just don't think we should do them yet. My suggestion is to open an issue and mark it as 3.0 milestone, and close this PR for now, and re-open once we are close to the 3.0 release.

2022-02-03 22:15 UTC, joperezr commented
After doing some additional checks and with the help of @ericstj, we found that actually this wouldn't be a breaking change since all of the package dependencies that are being removed from "net6.0" here already have a matching assembly identity that ships inbox and tooling will prefer over the NuGet packages, which means that when targeting "net6.0" these extra nuget dependencies would have never even made it to the compiler anyway. Because of that, I'm fine with going ahead and merging this now, as this is no longer considered a breaking change.

2022-02-03 22:16 UTC, joperezr approved these changes

2022-02-03 22:16 UTC, merged

2022-02-03 22:16 UTC, joperezr commented
Thanks for the fix @tibel, and sorry for the initial confusion here.